export enum UserRole {
  CUSTOMER = "CUSTOMER",
  RIDER = "RIDER",
  ORGANIZER = "ORGANIZER",
  BUSINESS_OWNER = "BUSINESS_OWNER",
  ADMIN = "ADMIN",
  SUPER_ADMIN = "SUPER_ADMIN",
}

export enum AccountStatus {
  ACTIVE = "ACTIVE",
  UNDER_REVIEW = "UNDER_REVIEW",
  REJECTED = "REJECTED",
  PENDING = "PENDING",
  PENDING_VERIFICATION = "PENDING_VERIFICATION",
}