import { CheckCircle2, Lock, Camera } from "lucide-react";

export default function DeliveryTypesSection() {
  return (
    <section className="py-16 bg-white border-t border-neutral-200/60">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
        <div className="text-center max-w-xl mx-auto space-y-2">
          <h2 className="text-xs font-bold text-emerald-600 uppercase tracking-widest">
            Verification Modes
          </h2>
          <h3 className="text-3xl font-black text-neutral-900">
            Choose Your Preferred Delivery Type
          </h3>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* PIN Delivery */}
          <div className="p-6 sm:p-8 rounded-3xl bg-neutral-50 border border-neutral-200 space-y-6">
            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-2xl bg-emerald-600 text-white">
                <Lock size={22} />
              </div>
              <div>
                <h4 className="text-xl font-bold text-neutral-900">Standard PIN Delivery</h4>
                <p className="text-xs text-neutral-500">Receiver gives 4-digit code to courier</p>
              </div>
            </div>
            <p className="text-xs text-neutral-600 leading-relaxed">
              Ideal for direct hand-offs. The courier enters the 4-digit PIN generated by the receiver on arrival to complete the parcel delivery securely.
            </p>
          </div>

          {/* Contactless Smart Delivery */}
          <div className="p-6 sm:p-8 rounded-3xl bg-emerald-50/50 border border-emerald-200 space-y-6">
            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-2xl bg-emerald-700 text-white">
                <Camera size={22} />
              </div>
              <div>
                <h4 className="text-xl font-bold text-neutral-900">Smart Contactless Delivery</h4>
                <p className="text-xs text-neutral-600">Proof-of-delivery photo & GPS verification</p>
              </div>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-center pt-2">
              <div className="p-3 rounded-xl bg-white border border-neutral-200 space-y-1.5">
                <div className="w-7 h-7 rounded-full bg-neutral-200 text-neutral-700 text-xs font-bold flex items-center justify-center mx-auto">
                  1
                </div>
                <p className="text-[11px] font-bold text-neutral-800">Receiver Away</p>
              </div>
              <div className="p-3 rounded-xl bg-white border border-neutral-200 space-y-1.5">
                <div className="w-7 h-7 rounded-full bg-neutral-200 text-neutral-700 text-xs font-bold flex items-center justify-center mx-auto">
                  2
                </div>
                <p className="text-[11px] font-bold text-neutral-800">3 Photos Taken</p>
              </div>
              <div className="p-3 rounded-xl bg-white border border-neutral-200 space-y-1.5">
                <div className="w-7 h-7 rounded-full bg-neutral-200 text-neutral-700 text-xs font-bold flex items-center justify-center mx-auto">
                  3
                </div>
                <p className="text-[11px] font-bold text-neutral-800">GPS Timestamp</p>
              </div>
              <div className="p-3 rounded-xl bg-emerald-100 border border-emerald-300 space-y-1.5">
                <CheckCircle2 size={18} className="text-emerald-700 mx-auto" />
                <p className="text-[11px] font-bold text-emerald-900">Proof Submitted</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}